<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-android</TargetFrameworks>

		<OutputType>Exe</OutputType>
		<RootNamespace>Mizan.App</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>Planör</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.mizan.app</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>0.3.0</ApplicationDisplayVersion>
		<ApplicationVersion>6</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<AndroidPackageFormat>apk</AndroidPackageFormat>
		<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#1E232A" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#1E232A" BaseSize="128,128" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" VersionOverride="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Mizan.Domain\Mizan.Domain.csproj" />
	  <ProjectReference Include="..\Mizan.Application\Mizan.Application.csproj" />
	  <ProjectReference Include="..\Mizan.Infrastructure\Mizan.Infrastructure.csproj" />
	  <ProjectReference Include="..\Mizan.Presentation\Mizan.Presentation.csproj" />
	</ItemGroup>

</Project>
