<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Mizan.Domain\Mizan.Domain.csproj" />
    <ProjectReference Include="..\..\src\Mizan.Application\Mizan.Application.csproj" />
    <ProjectReference Include="..\..\src\Mizan.Infrastructure\Mizan.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Mizan.Presentation\Mizan.Presentation.csproj" />
    <ProjectReference Include="..\..\tools\Mizan.ApkVerifier\Mizan.ApkVerifier.csproj" />
    <ProjectReference Include="..\..\tools\Mizan.ReleaseNotes\Mizan.ReleaseNotes.csproj" />
  </ItemGroup>

</Project>
